//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.7.10;Initial Catalog=QuanLyVoucher;User ID=sa;Password=sa@123" +
            "")]
        public string QuanLyVoucherConnectionString {
            get {
                return ((string)(this["QuanLyVoucherConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.250.10;Initial Catalog=QuanLyVoucher;Persist Security Info=Tr" +
            "ue;User ID=sa;Password=sa@123")]
        public string QuanLyVoucherConnectionString1 {
            get {
                return ((string)(this["QuanLyVoucherConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.201.66;Initial Catalog=QuanLyVoucher;Persist Security Info=Tr" +
            "ue;User ID=sa;Password=sa@123")]
        public string QuanLyVoucherConnectionString2 {
            get {
                return ((string)(this["QuanLyVoucherConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=vpmay6;Initial Catalog=QuanLyVoucher;Persist Security Info=True;User " +
            "ID=sa;Password=sa@123")]
        public string QuanLyVoucherConnectionString3 {
            get {
                return ((string)(this["QuanLyVoucherConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.10.10;Initial Catalog=QuanLyVoucher;Persist Security Info=True" +
            ";User ID=sa;Password=sa@123")]
        public string QuanLyVoucherConnectionString4 {
            get {
                return ((string)(this["QuanLyVoucherConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.10.10;Initial Catalog=QuanLyVoucher;Persist Security Info=True" +
            ";User ID=admin;Password=sa@123$")]
        public string QuanLyVoucherConnectionString5 {
            get {
                return ((string)(this["QuanLyVoucherConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SRIT002\\SQLEXPRESS;Initial Catalog=QuanLyVoucher;Persist Security Inf" +
            "o=True;User ID=sa;Password=P@ssw0rd")]
        public string QuanLyVoucherConnectionString6 {
            get {
                return ((string)(this["QuanLyVoucherConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.10.8;Initial Catalog=QuanLyVoucher;User ID=sa")]
        public string QuanLyVoucherConnectionString7 {
            get {
                return ((string)(this["QuanLyVoucherConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.10.8;Initial Catalog=QuanLyVoucher;User ID=sa;Password=sa@123")]
        public string QuanLyVoucherConnectionString8 {
            get {
                return ((string)(this["QuanLyVoucherConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.10.8;Initial Catalog=CRM-HHH;User ID=sa;Password=sa@123")]
        public string CRM_HHHConnectionString {
            get {
                return ((string)(this["CRM_HHHConnectionString"]));
            }
        }
    }
}
